language: java
sudo: required
dist: trusty
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
matrix:
  include:
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: openjdk11
install:
  - mvn clean install -DskipTests=true
script:
  - mvn clean test -DstorageEngine=InMemory
  - mvn clean test -DstorageEngine=MapDB
notifications:
  email:
    on_success: never
    on_failure: always
